
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTITY OBJECT_INDEX ARRAY_ITERATOR ARRAY_INDEX ARRAY_SLICEfilter_chain : filter_chain filter\n                        | filterfilter : IDENTITYfilter : OBJECT_INDEXfilter : ARRAY_ITERATORfilter : ARRAY_INDEXfilter : ARRAY_SLICE'
    
_lr_action_items = {'IDENTITY':([0,1,2,3,4,5,6,7,8,],[3,3,-2,-3,-4,-5,-6,-7,-1,]),'OBJECT_INDEX':([0,1,2,3,4,5,6,7,8,],[4,4,-2,-3,-4,-5,-6,-7,-1,]),'ARRAY_ITERATOR':([0,1,2,3,4,5,6,7,8,],[5,5,-2,-3,-4,-5,-6,-7,-1,]),'ARRAY_INDEX':([0,1,2,3,4,5,6,7,8,],[6,6,-2,-3,-4,-5,-6,-7,-1,]),'ARRAY_SLICE':([0,1,2,3,4,5,6,7,8,],[7,7,-2,-3,-4,-5,-6,-7,-1,]),'$end':([1,2,3,4,5,6,7,8,],[0,-2,-3,-4,-5,-6,-7,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'filter_chain':([0,],[1,]),'filter':([0,1,],[2,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> filter_chain","S'",1,None,None,None),
  ('filter_chain -> filter_chain filter','filter_chain',2,'p_filter_chain','ast.py',79),
  ('filter_chain -> filter','filter_chain',1,'p_filter_chain','ast.py',80),
  ('filter -> IDENTITY','filter',1,'p_filter_identity','ast.py',88),
  ('filter -> OBJECT_INDEX','filter',1,'p_filter_object_index','ast.py',92),
  ('filter -> ARRAY_ITERATOR','filter',1,'p_filter_array_iterator','ast.py',112),
  ('filter -> ARRAY_INDEX','filter',1,'p_filter_array_index','ast.py',127),
  ('filter -> ARRAY_SLICE','filter',1,'p_filter_array_slice','ast.py',141),
]
